#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.24.1
#  in conjunction with Tcl version 8.6
#    Nov 21, 2019 10:46:21 PM IST  platform: Windows NT

import sys
from hashlib import md5
from base64 import b64decode
from base64 import b64encode
#from q import m,f,k
from stegano import lsb
import tkinter.messagebox
from Crypto.Cipher import AES
from Crypto.Random import get_random_bytes
from Crypto.Util.Padding import pad, unpad
from tkinter import filedialog
from tkinter import *
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import DecryptionProcess_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    DecryptionProcess_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    DecryptionProcess_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def brws(self):
        root = Tk()
        root.filename = filedialog.askopenfilename(initialdir="C:/Users/jithu/PycharmProjects/j/MAJOR/",
                                                   title="Select file",
                                                   filetypes=(("Video files", "*.mp4"), ("All files", "*.*")))
        print(root.filename)
        file = open("binpath.txt", "r+")
        a = file.read()
        if(a==root.filename):
            self.Entry1.insert(10, root.filename)
            self.Button3.configure(state=ACTIVE)

        else:
            tkinter.messagebox.showerror(title="Video Stegnography", message="No Data Found")
            self.Button3.configure(state=DISABLED)

    def initi(self):
        print("")
    def decr(self):
        if (self.Entry2.get() == ""):
            tkinter.messagebox.showerror(title="Video Stegnography", message="Please Enter the key!!")
        else:
            file = open("bin.txt", "r+")
            a = file.read()
            b = a.split(",")
            global me
            me = b[2]
            #print(me)

            # self.Entry2.insert(10,me)
            class AESCipher:
                def __init__(self, key):
                    self.key = md5(key.encode('utf8')).digest()

                def decrypt(self, data):
                    raw = b64decode(data)
                    self.cipher = AES.new(self.key, AES.MODE_CBC, raw[:AES.block_size])
                    return unpad(self.cipher.decrypt(raw[AES.block_size:]), AES.block_size)

            cte = me
            # cte = input('Ciphertext: ')
            pwd = self.Entry2.get()

            prr = AESCipher(pwd).decrypt(cte).decode('utf-8')
            self.Entry3.insert(10, prr)
            # tk.messagebox.showinfo("Data",prr)

    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {Times New Roman} -size 16 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"
        font12 = "-family {Times New Roman} -size 20 -weight bold "  \
            "-slant roman -underline 0 -overstrike 0"

        top.geometry("1063x573+366+150")
        top.title("Decryption Process")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.122, rely=0.227, height=43, width=179)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(font=font12)
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''Select Video''')

        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.122, rely=0.401, height=43, width=179)
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(activeforeground="black")
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(font=font12)
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(highlightbackground="#d9d9d9")
        self.Label2.configure(highlightcolor="black")
        self.Label2.configure(text='''Key''')

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.122, rely=0.558, height=43, width=179)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(activeforeground="black")
        self.Label3.configure(background="#d9d9d9")
        self.Label3.configure(disabledforeground="#a3a3a3")
        self.Label3.configure(font=font12)
        self.Label3.configure(foreground="#000000")
        self.Label3.configure(highlightbackground="#d9d9d9")
        self.Label3.configure(highlightcolor="black")
        self.Label3.configure(text='''Message''')

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.348, rely=0.236,height=36, relwidth=0.371)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")
        self.Entry1.configure(width=394)

        self.Entry2 = tk.Entry(top)
        self.Entry2.place(relx=0.348, rely=0.419,height=36, relwidth=0.371)
        self.Entry2.configure(background="white")
        self.Entry2.configure(disabledforeground="#a3a3a3")
        self.Entry2.configure(font="TkFixedFont")
        self.Entry2.configure(foreground="#000000")
        self.Entry2.configure(highlightbackground="#d9d9d9")
        self.Entry2.configure(highlightcolor="black")
        self.Entry2.configure(insertbackground="black")
        self.Entry2.configure(selectbackground="#c4c4c4")
        self.Entry2.configure(selectforeground="black")
        self.Entry2.configure(show="*")

        self.Entry3 = tk.Entry(top)
        self.Entry3.place(relx=0.348, rely=0.576,height=36, relwidth=0.371)
        self.Entry3.configure(background="white")
        self.Entry3.configure(disabledforeground="#a3a3a3")
        self.Entry3.configure(font="TkFixedFont")
        self.Entry3.configure(foreground="#000000")
        self.Entry3.configure(highlightbackground="#d9d9d9")
        self.Entry3.configure(highlightcolor="black")
        self.Entry3.configure(insertbackground="black")
        self.Entry3.configure(selectbackground="#c4c4c4")
        self.Entry3.configure(selectforeground="black")

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.762, rely=0.236, height=45, width=150)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font10)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''Browse''',command=self.brws)
        self.Button1.configure(width=150)

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.593, rely=0.785, height=52, width=189)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font=font10)
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''Close''',command=exit)
        self.Button2.configure(width=189)

        self.Button3 = tk.Button(top)
        self.Button3.place(relx=0.357, rely=0.785, height=52, width=189)
        self.Button3.configure(activebackground="#ececec")
        self.Button3.configure(activeforeground="#000000")
        self.Button3.configure(background="#d9d9d9")
        self.Button3.configure(disabledforeground="#a3a3a3")
        self.Button3.configure(font=font10)
        self.Button3.configure(foreground="#000000")
        self.Button3.configure(highlightbackground="#d9d9d9")
        self.Button3.configure(highlightcolor="black")
        self.Button3.configure(pady="0")
        self.Button3.configure(text='''Load''',command=self.decr)
        self.Button3.configure(state=DISABLED)

if __name__ == '__main__':
    vp_start_gui()





