#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.24.1
#  in conjunction with Tcl version 8.6
#    Nov 19, 2019 12:30:48 AM IST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import UI003_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    UI003_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    UI003_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def getv(self):
        global m
        global f
        global k
        l=[]
        m=self.e1.get()
        f=self.e2.get()
        #k=self.e3.get()
        l=[m,f]

        file=open("bin.txt","w+")
        for i in range(0,2):
            file.write(l[i]+",")
        file.close()
        exit()
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {Segoe UI} -size 12 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"

        top.geometry("809x489+441+150")
        top.title("UI003")
        top.configure(background="#d9d9d9")

        self.Frame1 = tk.Frame(top)
        self.Frame1.place(relx=0.087, rely=0.082, relheight=0.787
                , relwidth=0.834)
        self.Frame1.configure(relief='groove')
        self.Frame1.configure(borderwidth="2")
        self.Frame1.configure(relief="groove")
        self.Frame1.configure(background="#d9d9d9")
        self.Frame1.configure(width=675)

        self.lb1 = tk.Label(self.Frame1)
        self.lb1.place(relx=0.089, rely=0.104, height=56, width=246)
        self.lb1.configure(background="#d9d9d9")
        self.lb1.configure(disabledforeground="#a3a3a3")
        self.lb1.configure(font=font10)
        self.lb1.configure(foreground="#000000")
        self.lb1.configure(text='''Enter the Message''')
        self.lb1.configure(width=246)

        self.lb2 = tk.Label(self.Frame1)
        self.lb2.place(relx=0.074, rely=0.424, height=56, width=246)
        self.lb2.configure(background="#d9d9d9")
        self.lb2.configure(disabledforeground="#a3a3a3")
        self.lb2.configure(font=font10)
        self.lb2.configure(foreground="#000000")
        self.lb2.configure(text='''Enter the Key''')

        """self.lb3 = tk.Label(self.Frame1)
        self.lb3.place(relx=0.089, rely=0.468, height=56, width=246)
        self.lb3.configure(background="#d9d9d9")
        self.lb3.configure(disabledforeground="#a3a3a3")
        self.lb3.configure(font=font10)
        self.lb3.configure(foreground="#000000")
        self.lb3.configure(text='''New File Name''')"""

        self.e1 = tk.Entry(self.Frame1)
        self.e1.place(relx=0.578, rely=0.13,height=40, relwidth=0.333)
        self.e1.configure(background="white")
        self.e1.configure(disabledforeground="#a3a3a3")
        self.e1.configure(font="TkFixedFont")
        self.e1.configure(foreground="#000000")
        self.e1.configure(insertbackground="black")

        self.e2 = tk.Entry(self.Frame1)
        self.e2.place(relx=0.578, rely=0.450,height=40, relwidth=0.333)
        self.e2.configure(background="white")
        self.e2.configure(disabledforeground="#a3a3a3")
        self.e2.configure(font="TkFixedFont")
        self.e2.configure(foreground="#000000")
        self.e2.configure(insertbackground="black")

        """self.e3 = tk.Entry(self.Frame1)
        self.e3.place(relx=0.578, rely=0.494,height=40, relwidth=0.333)
        self.e3.configure(background="white")
        self.e3.configure(disabledforeground="#a3a3a3")
        self.e3.configure(font="TkFixedFont")
        self.e3.configure(foreground="#000000")
        self.e3.configure(insertbackground="black")"""

        self.btn1 = tk.Button(self.Frame1)
        self.btn1.place(relx=0.37, rely=0.779, height=53, width=214)
        self.btn1.configure(activebackground="#ececec")
        self.btn1.configure(activeforeground="#000000")
        self.btn1.configure(background="#d9d9d9")
        self.btn1.configure(disabledforeground="#a3a3a3")
        self.btn1.configure(font=font10)
        self.btn1.configure(foreground="#000000")
        self.btn1.configure(highlightbackground="#d9d9d9")
        self.btn1.configure(highlightcolor="black")
        self.btn1.configure(pady="0")
        self.btn1.configure(text='''SUBMIT''',command=self.getv)
        self.btn1.configure(width=214)

if __name__ == '__main__':
    vp_start_gui()





