#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.24.1
#  in conjunction with Tcl version 8.6
#    Nov 21, 2019 08:26:03 PM IST  platform: Windows NT

import sys
import os
try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import VideoSteganography_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    VideoSteganography_support.init(root, top)
    root.mainloop()

w = None
def create_Toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    top = Toplevel1 (w)
    VideoSteganography_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_Toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def encr(self):
        os.system("Videoselection.py")
    def decr(self):
        os.system("DecryptionProcess.py")
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'
        font10 = "-family {Segoe UI} -size 40 -weight bold -slant "  \
            "roman -underline 0 -overstrike 0"
        font9 = "-family {Segoe UI} -size 28 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.geometry("1910x979+0+8")
        top.title("Video Steganography")
        top.configure(background="#add8d2")
        top.configure(highlightbackground="#c2e0ef")
        top.configure(highlightcolor="#c3d9db")

        self.menubar = tk.Menu(top,font="TkMenuFont",bg=_bgcolor,fg=_fgcolor)
        top.configure(menu = self.menubar)

        self.lb1 = tk.Label(top)
        self.lb1.place(relx=0.267, rely=0.082, height=136, width=875)
        self.lb1.configure(activebackground="#f9f9f9")
        self.lb1.configure(activeforeground="black")
        self.lb1.configure(anchor='n')
        self.lb1.configure(background="#add8d2")
        self.lb1.configure(disabledforeground="#a3a3a3")
        self.lb1.configure(font=font10)
        self.lb1.configure(foreground="#ff1605")
        self.lb1.configure(highlightbackground="#d9d9d9")
        self.lb1.configure(highlightcolor="#646464646464")
        self.lb1.configure(text='''VIDEO STEGANOGRAPHY''')

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.314, rely=0.388, height=107, width=670)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(font=font9)
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''ENCRYPT''',command=self.encr)

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.314, rely=0.582, height=107, width=670)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(font=font9)
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''DECRYPT''',command=self.decr)

if __name__ == '__main__':
    vp_start_gui()





